### ISSUE TITLE
Version 2.0.2 not available on pub.dev

### ISSUE THREAD

**Issue by frankperez87** [lohanidamodar/pdf_viewer#117]
The latest release of version 2.0.2 is tagged in GitHub but not available on pub.dev

I've tried this version on Android and it seems to solve the crashing issue that everyone is having. Is there any reason I cannot use this version, or can we get that on to pub.dev to use?

To use it in the meantime within my project I updated my pubspec.yaml to show like this
```
  advance_pdf_viewer:
    git:
      url: git@github.com:lohanidamodar/pdf_viewer.git
      ref: 4e5d96be29de515f1081c0b6897741b8dca84722
```

**Comment by mumairofficial** [comment]
@frankperez87 I am getting this error after trying purposed solution. I think this is something related to my configurations but can you help me?
```
pub get failed (server unavailable) -- attempting retry 7 in 64 seconds...
Git error. Command: `git clone --mirror git@github.com:lohanidamodar/pdf_viewer.git /Users/username/Developer/flutter/.pub-cache/git/cache/pdf_viewer-82ab6a243193a92c143e8d94d0f623fb0f089a6e`
stdout: 
stderr: Cloning into bare repository '/Users/username/Developer/flutter/.pub-cache/git/cache/pdf_viewer-82ab6a243193a92c143e8d94d0f623fb0f089a6e'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
exit code: 128
```

**Comment by mumairofficial** [comment]
I figured it out, `ssh` was messed up so I use the `https`, following worked for me:

```yaml
  advance_pdf_viewer:
    git:
      url: https://github.com/lohanidamodar/pdf_viewer.git
      ref: 4e5d96be29de515f1081c0b6897741b8dca84722
```
